# Generated by Django 4.0.7 on 2023-06-04 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nf_core', '0042_smsschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsAggregatorCentralPlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=50)),
                ('operator_type', models.CharField(choices=[('MNO', 'MNO'), ('IPTSP', 'IPTSP')], default='MNO', max_length=5)),
                ('send_sms_url', models.URLField(default='https://api.mnpspbd.com/a2p-sms/api/v1/send-sms')),
                ('delivery_status_url', models.URLField(default='https://api.mnpspbd.com/a2p-proxy-api/api/v1/check-delivery-report')),
                ('check_balance_url', models.URLField(default='https://api.mnpspbd.com/a2p-proxy-api/api/v1/check-credit-balance')),
                ('check_cli_url', models.URLField(default='https://api.mnpspbd.com/a2p-proxy-api/api/v1/check-cli')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sms_config_aggregator_centralplatform',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SmsAggregatorOperatorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(max_length=20)),
                ('operator_prefix', models.CharField(max_length=4, unique=True)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('bill_msisdn', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nf_core.smsaggregatorcentralplatformconfig')),
            ],
            options={
                'db_table': 'sms_config_aggregator_operator',
                'managed': True,
            },
        ),
        # migrations.AddField(
        #     model_name='smsqueuehandler',
        #     name='updated_at',
        #     field=models.DateTimeField(auto_now=True),
        # ),
        migrations.CreateModel(
            name='SmsUserOperatorCredentialConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_masking_enabled', models.BooleanField(default=False)),
                ('cli', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nf_core.smsaggregatoroperatorconfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sms_config_user_operator_credential',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SmsUserDestinationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_operator_name',
                 models.CharField(choices=[('Grameenphone', 'Grameenphone'), ('Banglalink', 'Banglalink'), ('TeleTalk', 'TeleTalk'), ('Robi', 'Robi')], max_length=20)),
                ('destination_operator_prefix', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aggregator_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nf_core.smsaggregatoroperatorconfig')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sms_config_user_destination_operator',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='smsaggregatorcentralplatformconfig',
            index=models.Index(fields=['operator_type'], name='sms_config__operato_47d448_idx'),
        ),
        migrations.AddIndex(
            model_name='smsuseroperatorcredentialconfig',
            index=models.Index(fields=['user', 'operator'], name='sms_config__user_id_92803d_idx'),
        ),
        migrations.AddConstraint(
            model_name='smsuseroperatorcredentialconfig',
            constraint=models.UniqueConstraint(fields=('user', 'operator'), name='unique_user_operator'),
        ),
        migrations.AddIndex(
            model_name='smsuserdestinationconfig',
            index=models.Index(fields=['user', 'destination_operator_prefix'], name='sms_config__user_id_cf22b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='smsuserdestinationconfig',
            constraint=models.UniqueConstraint(fields=('user', 'destination_operator_prefix'), name='unique_user_destinationoperator'),
        ),
        migrations.AddIndex(
            model_name='smsaggregatoroperatorconfig',
            index=models.Index(fields=['operator_prefix'], name='sms_config__operato_f84a1d_idx'),
        ),
    ]
