# Generated by Django 4.0.7 on 2023-05-23 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nf_core', '0043_smsaggregatorcentralplatformconfig_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smsaggregatorcentralplatformconfig',
            options={'managed': True, 'verbose_name': 'SMS Aggregator Central Platform Config'},
        ),
        migrations.AlterModelOptions(
            name='smsuserdestinationconfig',
            options={'managed': True, 'verbose_name': 'SMS User Destination Config'},
        ),
        migrations.AlterModelOptions(
            name='smsuseroperatorcredentialconfig',
            options={'managed': True, 'verbose_name': 'SMS User Operator Credential Config'},
        ),
    ]
