# Generated by Django 4.0.7 on 2023-05-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nf_core', '0044_alter_smsaggregatorcentralplatformconfig_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsuseroperatorcredentialconfig',
            name='operator_name',
            field=models.CharField(choices=[('Grameenphone', 'Grameenphone'), ('Banglalink', 'Banglalink'), ('TeleTalk', 'TeleTalk'), ('Robi', 'Robi'), ('Agni', 'Agni'), ('BanglaPhone', 'BanglaPhone'), ('BijoyPhone', 'BijoyPhone'), ('DhakaPhone', 'DhakaPhone'), ('NationalPhone', 'NationalPhone'), ('Onetel', 'Onetel'), ('PeoplesTel', 'PeoplesTel'), ('RanksTel', 'RanksTel'), ('ShebaPhone', 'ShebaPhone'), ('Telebarta', 'Telebarta')], max_length=20),
        ),
    ]
