# Generated by Django 4.0.7 on 2023-06-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('nf_core', '0044_smsoperatorlist_smsqueuehandler_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsaggregatorcentralplatformconfig',
            name='api_key',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='smsaggregatoroperatorconfig',
            name='bill_msisdn',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='smsaggregatoroperatorconfig',
            name='operator_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='smsaggregatoroperatorconfig',
            name='operator_prefix',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='smsaggregatoroperatorconfig',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='smsaggregatoroperatorconfig',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='smsuserdestinationconfig',
            name='destination_operator_name',
            field=models.CharField(choices=[('Grameenphone', 'Grameenphone'), ('Banglalink', 'Banglalink'), ('TeleTalk', 'TeleTalk'), ('Robi', 'Robi')], max_length=100),
        ),
        migrations.AlterField(
            model_name='smsuserdestinationconfig',
            name='destination_operator_prefix',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='smsuseroperatorcredentialconfig',
            name='cli',
            field=models.CharField(max_length=100),
        ),
    ]
