# Generated by Django 4.0.7 on 2023-06-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('nf_core', '0045_smsqueuehandler_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsaggregatoroperatorconfig',
            name='operator_prefix',
            field=models.CharField(max_length=10),
        ),
    ]
