# Generated by Django 4.0.7 on 2023-06-07 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nf_core', '0047_smsusercliconfig_and_more'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='SmsUserDestinationOperatorConfig',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('destination_operator_name', models.CharField(max_length=100)),
        #         ('destination_operator_prefix', models.CharField(max_length=10)),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('updated_at', models.DateTimeField(auto_now=True)),
        #         ('aggregator_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nf_core.smsaggregatoroperatorconfig')),
        #         ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        #     ],
        #     options={
        #         'db_table': 'sms_config_user_destination_operator',
        #         'managed': True,
        #     },
        # ),
        migrations.AddField(
            model_name='smsaggregatorcentralplatformconfig',
            name='default_bill_msisdn',
            field=models.CharField(default='', max_length=100),
        ),
        # migrations.AddField(
        #     model_name='smsqueuehandler',
        #     name='updated_at',
        #     field=models.DateTimeField(auto_now=True),
        # ),
        migrations.AlterField(
            model_name='smsaggregatorcentralplatformconfig',
            name='operator_type',
            field=models.CharField(default='MNO', max_length=5),
        ),
        migrations.AlterField(
            model_name='smsoperatorlist',
            name='operator_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='smsoperatorlist',
            name='operator_prefix',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='smsoperatorlist',
            name='operator_type',
            field=models.CharField(default='MNO', max_length=5),
        ),
        migrations.DeleteModel(
            name='SmsUserDestinationConfig',
        ),
        # migrations.AddIndex(
        #     model_name='smsuserdestinationoperatorconfig',
        #     index=models.Index(fields=['user', 'destination_operator_prefix'], name='sms_config__user_id_cf22b9_idx'),
        # ),
        # migrations.AddConstraint(
        #     model_name='smsuserdestinationoperatorconfig',
        #     constraint=models.UniqueConstraint(fields=('user', 'destination_operator_prefix'), name='unique_user_destinationoperator'),
        # ),
    ]
